# Generated by Django 2.2.5 on 2021-10-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdvertiserId', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=30)),
                ('Link', models.TextField()),
                ('Clicks', models.IntegerField()),
                ('Views', models.IntegerField()),
                ('Image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Clicks', models.IntegerField()),
                ('Views', models.IntegerField()),
            ],
        ),
    ]
