# Generated by Django 2.2.5 on 2021-10-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_auto_20211010_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='Image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='Views',
            field=models.IntegerField(null=True),
        ),
    ]
