# Generated by Django 2.2.5 on 2021-10-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0004_auto_20211011_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='Approve',
            field=models.BooleanField(default=False),
        ),
    ]
